name: Build OPNsense for Raspberry Pi (FreeBSD)

on:
  push:
    branches:
      - master  #

jobs:
  build-freebsd:
    runs-on: ubuntu-latest  # Or a suitable Linux runner (VM support required)
    steps:
      - name: Set up FreeBSD VM
        uses: vmactions/freebsd-vm@v1.0.8  # Replace with desired version

      - name: Download FreeBSD image
        run: |
          sudo wget ${{ secrets.FREEBSD_IMAGE_URL }} -O /tmp/FreeBSD-13.2-RELEASE-arm64-aarch64-RPI.img.xz

      - name: Unpack FreeBSD image
        run: |
          sudo mkdir /mnt/freebsd
          sudo xzcat /tmp/FreeBSD-13.2-RELEASE-arm64-aarch64-RPI.img.xz | sudo dd of=/mnt/freebsd/FreeBSD-image.img status=progress bs=16M

      - name: Mount FreeBSD image (within the VM)
        run: |
          sudo kldload loop
          sudo mdconfig -a -t vnode -f /mnt/freebsd/FreeBSD-image.img  # Use mounted image path
          loopbackDevice=$(mdconfig -l | grep -Eo 'md[0-9]+')
          sudo mkdir /mnt/freebsd
          sudo mount -t ffs /dev/${loopbackDevice} /mnt/freebsd

      - name: Chroot into FreeBSD
        run: |
          sudo chroot /mnt/freebsd /bin/bash -c "
            echo 'uart_2ndstage=1\nenable_uart=1' | sudo tee -a /boot/config.txt
            echo 'over_voltage=6\narm_freq=2000' | sudo tee -a /boot/config.txt

            # Enable powerd
            sysrc powerd_enable=\"YES\"
            /etc/rc.d/powerd restart

            # Sync time
            ntpdate pool.ntp.org

            # Update the system
            pkg update
            pkg upgrade

            # Install tools
            pkg install -y sudo git rpi-firmware u-boot-rpi4

            # Set up sudoers
            echo 'Defaults env_keep += \"HOME\"\n%wheel ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers.d/wheel

            # Get IP address
            ifconfig genet0 | grep inet >> /tmp/rpi_ip.txt
          "

      - name: Set up build environment (within the VM)
        run: |
          sudo apt update
          sudo apt install -y git wget xz-utils

      - name: Clone OPNsense tools (within the VM)
        run: |
          sudo mkdir /usr/tools
          sudo git clone --depth=1 https://github.com/opnsense/tools.git /usr/tools
          sudo make -C /usr/tools update

      # ... Remaining steps for building OPNsense (within the VM) are likely similar to the previous version ...

      - name: Upload built image (optional)
        uses: actions/upload-artifact@v3
        with:
          name: opnsense-image
          path: /usr/local/opnsense/build/${{ secrets.OPNSENSE_VERSION }}[0:2]/aarch64/images/OPNsense-${{ secrets.OPNSENSE_VERSION }}-arm-aarch64-RPI.img

      - name: Unmount FreeBSD (within the VM)
        run: |
          sudo umount /mnt/freebsd
          sudo rmdir /mnt/freebsd

      - name: Output instructions (optional)
        run: |
          echo "OPNsense image built successfully!"
          echo "Download the image from the artifacts tab and transfer it to your Raspberry Pi."

